export const environment = {
  production: true,
  isDebugEnable: false,
  // endpointRedirectS3: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/',
  // endpointAddPerson: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/add/person/',
  // endPointAddRefer: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/',
  // endPointReferAccept: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/accept/',
  // endPointValidateTokenForm: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/validate/link/',
  // endpointSendConfirmation: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/confirmacion/',
  // endPointForwardEmail: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/forward/mail/',
  // endpointConfirmationToken: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/activacion/',
  // endpointLogin: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/login/',
  // endPointForwardToken: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/forward/confirmation/',
  // endPointSendEmailPassword: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/recover/account/',
  // endPointResetPassword: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/reset/password/now/',
  // endPointGraphicalData: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/get/graphical/data/',
  // endPointGetReferrals: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/get/referrals/',
  // endPointHome: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/',
  // endPointRedirectForm: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/vincular',
  // endpointHealth: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/health',

  // endpointRedirectS3: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/',
  // endpointAddPerson: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/add/person/',
  // endPointAddReferCdt: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/cdt/',
  // endPointAddReferTdc: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/tcd/',
  // endPointReferAccept: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/accept/cdt/',
  // endPointReferTdc: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/accept/tcd/',
  // endPointValidateTokenForm: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/validate/link/',
  // endpointSendConfirmation: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/confirmacion/',
  // endPointForwardEmail: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/refer/forward/mail/',
  // endpointConfirmationToken: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/activacion/',
  // endpointLogin: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/login/',
  // endPointForwardToken: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/forward/confirmation/',
  // endPointSendEmailPassword: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/recover/account/',
  // endPointResetPassword: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/reset/password/now/',
  // endPointGraphicalData: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/get/graphical/data/',
  // endPointGetReferrals: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/get/referrals/',
  // endPointHome: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/',
  // endPointRedirectForm: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/vincular',
  // endPointRedirectFormTdc: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/vincular-tcd',
  // endPointRedirectTcd: 'https://digital.bancopichincha.com.co/tarjeta-de-credito',
  // endpointHealth: 'https://digital-idealab.bancopichinchadigital.co/amigos-pichincha/health',

  endpointRedirectS3: 'http://localhost:9010/amigos-pichincha/',
  endpointAddPerson: 'http://localhost:9010/amigos-pichincha/add/person/',
  endPointAddReferCdt: 'http://localhost:9010/amigos-pichincha/refer/cdt/',
  endPointAddReferTdc: 'http://localhost:9010/amigos-pichincha/refer/tcd/',
  endPointReferAccept: 'http://localhost:9010/amigos-pichincha/refer/accept/cdt/',
  endPointReferTdc: 'http://localhost:9010/amigos-pichincha/refer/accept/tcd/',
  endPointValidateTokenForm: 'http://localhost:9010/amigos-pichincha/validate/link/',
  endPointForwardEmail: 'http://localhost:9010/amigos-pichincha/refer/forward/mail/',
  endpointConfirmationToken: 'http://localhost:9010/amigos-pichincha/activacion/',
  endpointLogin: 'http://localhost:9010/amigos-pichincha/login/',
  endPointForwardToken: 'http://localhost:9010/amigos-pichincha/forward/confirmation/',
  endPointSendEmailPassword: 'http://localhost:9010/amigos-pichincha/recover/account/',
  endPointResetPassword: 'http://localhost:9010/amigos-pichincha/reset/password/now/',
  endPointGraphicalData: 'http://localhost:9010/amigos-pichincha/get/graphical/data/',
  endPointGetReferrals: 'http://localhost:9010/amigos-pichincha/get/referrals/',
  endPointHome: 'http://localhost:9010/amigos-pichincha/',
  endPointRedirectForm: 'http://localhost:9010/amigos-pichincha/vincular',
  endPointRedirectFormTdc: 'http://localhost:9010/amigos-pichincha/vincular-tcd',
  endPointRedirectTcd: 'https://digital.bancopichincha.com.co/tarjeta-de-credito',
  endpointHealth: 'http://localhost:9010/amigos-pichincha/health',
}