import { Component, OnInit, Input, SimpleChanges } from '@angular/core';
import { PersonRefered } from 'src/app/model/refered.model';
import { ReferidoService } from 'src/app/service/referido.service';
import { LoggerService } from 'src/app/service/common/logger.service';
import { ApiGeneralService } from 'src/app/service/common/api-general.service';
import { GeneralRequest } from 'src/app/model/general.request';
import { environment } from 'src/environments/environment';


@Component({
  selector: 'app-form-refer',
  templateUrl: './form-refer.component.html',
  styleUrls: ['./form-refer.component.scss']
})
export class FormReferComponent implements OnInit {
  @Input() path: string;
  @Input() token: string;
  rspReSendInvitation: any
  storage: any;
  rspAccept: any;  
  rspToken: any;
  dateExpedition: any;
  lstCities: any;
  route: Location;
  constructor(private referidoService: ReferidoService, private log: LoggerService, private apiService: ApiGeneralService, private generalRequest: GeneralRequest, private PersonRefered: PersonRefered) {
    this.storage = window.sessionStorage;
    this.route = location;
  }

  ngOnInit() {
    (document.getElementById('registrar-refered') as HTMLInputElement).disabled = true;
    // this.validateTokenService();
  }
  
  public reSendInvitation(){
     let msg = confirm('El tiempo de invitación para referirte ha caducado. Haz click en confirmar para reenviar invitación');
     if (msg) {
       this.resendEmailService();
     } else{
       alert('No se logró enviar nueva invitación');
     }
  }
  public getValue(event){
    this.dateExpedition = event;
  }

  private callbackAcceptRefer(): any {
    this.rspAccept = this.apiService.response;
    if(this.rspAccept[0].status == true ) {
      document.getElementById('myModalCdt').style.display = 'block';
      // this.route.reload();
    }
  } 

  public acceptReferService() {
    this.PersonRefered.document = (document.getElementById('numdocumentrefered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    // this.PersonRefered.documentType = (document.getElementById('type-id-refered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.dateExpedition = this.dateExpedition;
    this.PersonRefered.name = (document.getElementById('name-refered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.city = (document.getElementById('city-refered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.department = (document.getElementById('department-refered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.address = (document.getElementById('address-refered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.phone = (document.getElementById('numcelrefered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.email = (document.getElementById('emailrefered') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.codeRefer = (document.getElementById('codeProm') as HTMLInputElement).value.toLocaleLowerCase().trim();
    this.PersonRefered.termsConditions = (document.getElementById('accept-terms-refered') as HTMLInputElement).checked == true ? 'acepto' : ''
    this.PersonRefered.completedForm = 'si';
    this.PersonRefered.token = this.token;
    try {
      this.apiService.invokePostRequest<PersonRefered, boolean>(
        environment.endPointReferAccept,
        this.PersonRefered,
        (rsp: boolean) => {
          this.callbackAcceptRefer();
        }
      );
    } catch (err) {
      this.log.error(this, "Error consumiendo el servicio login: " + err);
    }
  }
  
  private callbackValidateToken() {
     this.rspToken = this.apiService.response;
     if(this.rspToken[0].status == true) {
        alert(this.rspToken[0].response);
     }
     if(this.rspToken[0].status == false){
       this.reSendInvitation();
     }
       return this.rspToken;
  } 

  public validateTokenService() {
     this.PersonRefered.token = this.token;
     try {
       this.apiService.invokePostRequest<PersonRefered, boolean>(
         environment.endPointValidateTokenForm + this.PersonRefered.token,
         this.PersonRefered,
         (rsp: boolean) => {
           this.callbackValidateToken();
         }
       );
     } catch (err) {
       this.log.error(this, "Error consumiendo el servicio login: " + err);
     }
  }

  public callBackReSendEmail(){
    this.rspReSendInvitation = this.apiService.response;
    if (this.rspReSendInvitation[0].status == true) {
      alert('Se ha reenviado invitación al correo registrado');
    }

  }

  public resendEmailService(){
    this.PersonRefered.token = this.token;
    try {
      this.apiService.invokePostRequest<PersonRefered, boolean>(
        environment.endPointForwardEmail + this.PersonRefered.token,
        this.PersonRefered,
        (rsp: boolean) => {
          this.callbackValidateToken();
        }
      );
    } catch (err) {
      this.log.error(this, "Error consumiendo el servicio login: " + err);
    }
  }

  public onlyNumbers(event: KeyboardEvent) {
    const input = event.target as HTMLInputElement;
    input.value = input.value.replace(/[^0-9]/g, '');

  }

  public onlyLetters(event: KeyboardEvent) {
    const input = event.target as HTMLInputElement;
    input.value = input.value.replace(/[^a-zA-ZáéíóúÁÉÍÓÚ ]/g, '');
  }

  public disabledButton() {
    let smll = document.querySelectorAll('small');
    smll.forEach(small => {
      if (small.style.display == 'block') {
        (document.getElementById('registrar-refered') as HTMLButtonElement).disabled = true;
      }
    });
  }

  public validateData() {
    let name = (document.getElementById('name-refered') as HTMLInputElement).value;
    let numid = (document.getElementById('numdocumentrefered') as HTMLInputElement).value;
    let depar = (document.getElementById('department-refered') as HTMLInputElement).value;
    let city = (document.getElementById('city-refered') as HTMLInputElement).value;
    let address = (document.getElementById('address-refered') as HTMLInputElement).value;
    let numcel = (document.getElementById('numcelrefered') as HTMLInputElement).value;
    let email = (document.getElementById('emailrefered') as HTMLInputElement).value;
    let terms = (document.getElementById('accept-terms-refered') as HTMLInputElement).checked;
    if (name != ""  && numid != "" && depar != "" && city != "" && address != "" && numcel != "" && email != "" && terms === true) {
      (document.getElementById('registrar-refered') as HTMLInputElement).disabled = false;
    } else {
      (document.getElementById('registrar-refered') as HTMLInputElement).disabled = true;
    }
  }

  public viewModal() {
    if ((document.getElementById('accept-terms-refered') as HTMLInputElement).checked == true) {
      document.getElementById('ModalTerms').style.display = 'block';
      document.body.style.overflow = 'hidden';
    } else if ((document.getElementById('accept-terms-refered') as HTMLInputElement).checked == false) {
      document.body.style.overflow = 'auto';
    }
  }

  public closeModal() {
    document.getElementById('ModalTerms').style.display = 'none';
    let v = (document.getElementById('accept-terms-refered') as HTMLInputElement).checked = false;
    document.body.style.overflow = 'auto';
  }
  public closeModalWithCheck() {
    let request = new PersonRefered();
    document.getElementById('ModalTerms').style.display = 'none';
    document.body.style.overflow = 'auto';
    request.termsConditions = (document.getElementById('accept-terms-refered') as HTMLInputElement).checked == true ? 'aceptado' : 'rechazado';
  }
  
   public optionCiudades(idDepartament) {
    //  let lst = "";
      let lst = "<option value=\">Selecciona...</option>"
      +"<option value=\"Amazonas - El Encanto\">El Encanto</option>"
      +"<option value=\"Amazonas - La Chorrera\">La Chorrera</option>"
      +"<option value=\"Amazonas - La Pedrera\">La Pedrera</option>"
      +"<option value=\"Amazonas - La Victoria\">La Victoria</option>"
      +"<option value=\"Amazonas - Leticia\">Leticia</option>"
      +"<option value=\"Amazonas - Mirití-Paraná\">Mirití-Paraná</option>"
      +"<option value=\"Amazonas - Puerto Alegría\">Puerto Alegría</option>"
      +"<option value=\"Amazonas - Puerto Arica\">Puerto Arica</option>"
      +"<option value=\"Amazonas - Puerto Nariño\">Puerto Nariño</option>"
      +"<option value=\"Amazonas - Puerto Santander\">Puerto Santander</option>"
      +"<option value=\"Amazonas - Tarapacá\">Tarapacá</option>";
      // +"<option value=\"Antioquia - Abejorral\">Abejorral</option>"
      // +"<option value=\"Antioquia - Abriaquí\">Abriaquí</option>"
      // +"<option value=\"Antioquia - Alejandría\">Alejandría</option>"
      // +"<option value=\"Antioquia - Amagá\">Amagá</option>"
      // +"<option value=\"Antioquia - Amalfi\">Amalfi</option>"
      // +"<option value=\"Antioquia - Andes\">Andes</option>"
      // +"<option value=\"Antioquia - Angelópolis\">Angelópolis</option>"
      // +"<option value=\"Antioquia - Angostura\">Angostura</option>"
      // +"<option value=\"Antioquia - Anorí\">Anorí</option>"
      // +"<option value=\"Antioquia - Anzá\">Anzá</option>"
      // +"<option value=\"Antioquia - Apartadó\">Apartadó</option>"
      // +"<option value=\"Antioquia - Arboletes\">Arboletes</option>"
      // +"<option value=\"Antioquia - Argelia\">Argelia</option>"
      // +"<option value=\"Antioquia - Armenia\">Armenia</option>"
      // +"<option value=\"Antioquia - Barbosa\">Barbosa</option>"
      // +"<option value=\"Antioquia - Bello\">Bello</option>"
      // +"<option value=\"Antioquia - Belmira\">Belmira</option>"
      // +"<option value=\"Antioquia - Betania\">Betania</option>"
      // +"<option value=\"Antioquia - Betulia\">Betulia</option>"
      // +"<option value=\"Antioquia - Briceño\">Briceño</option>"
      // +"<option value=\"Antioquia - Buriticá\">Buriticá</option>"
      // +"<option value=\"Antioquia - Cáceres\">Cáceres</option>"
      // +"<option value=\"Antioquia - Caicedo\">Caicedo</option>"
      // +"<option value=\"Antioquia - Caldas\">Caldas</option>"
      // +"<option value=\"Antioquia - Campamento\">Campamento</option>"
      // +"<option value=\"Antioquia - Cañasgordas\">Cañasgordas</option>"
      // +"<option value=\"Antioquia - Caracolí\">Caracolí</option>"
      // +"<option value=\"Antioquia - Caramanta\">Caramanta</option>"
      // +"<option value=\"Antioquia - Carepa\">Carepa</option>"
      // +"<option value=\"Antioquia - Carmen de Viboral\">Carmen de Viboral</option>"
      // +"<option value=\"Antioquia - Carolina del Príncipe\">Carolina del Príncipe</option>"
      // +"<option value=\"Antioquia - Caucasia\">Caucasia</option>"
      // +"<option value=\"Antioquia - Chigorodó\">Chigorodó</option>"
      // +"<option value=\"Antioquia - Cisneros\">Cisneros</option>"
      // +"<option value=\"Antioquia - Ciudad Bolívar\">Ciudad Bolívar</option>"
      // +"<option value=\"Antioquia - Cocorná\">Cocorná</option>"
      // +"<option value=\"Antioquia - Concepción\">Concepción</option>"
      // +"<option value=\"Antioquia - Concordia\">Concordia</option>"
      // +"<option value=\"Antioquia - Copacabana\">Copacabana</option>"
      // +"<option value=\"Antioquia - Dabeiba\">Dabeiba</option>"
      // +"<option value=\"Antioquia - Donmatías\">Donmatías</option>"
      // +"<option value=\"Antioquia - Ebéjico\">Ebéjico</option>"
      // +"<option value=\"Antioquia - El Bagre\">El Bagre</option>"
      // +"<option value=\"Antioquia - El Peñol\">El Peñol</option>"
      // +"<option value=\"Antioquia - El Retiro\">El Retiro</option>"
      // +"<option value=\"Antioquia - El Santuario\">El Santuario</option>"
      // +"<option value=\"Antioquia - Entrerríos\">Entrerríos</option>"
      // +"<option value=\"Antioquia - Envigado\">Envigado</option>"
      // +"<option value=\"Antioquia - Fredonia\">Fredonia</option>"
      // +"<option value=\"Antioquia - Frontino\">Frontino</option>"
      // +"<option value=\"Antioquia - Giraldo\">Giraldo</option>"
      // +"<option value=\"Antioquia - Girardota\">Girardota</option>"
      // +"<option value=\"Antioquia - Gómez Plata\">Gómez Plata</option>"
      // +"<option value=\"Antioquia - Granada\">Granada</option>"
      // +"<option value=\"Antioquia - Guadalupe\">Guadalupe</option>"
      // +"<option value=\"Antioquia - Guarne\">Guarne</option>"
      // +"<option value=\"Antioquia - Guatapé\">Guatapé</option>"
      // +"<option value=\"Antioquia - Heliconia\">Heliconia</option>"
      // +"<option value=\"Antioquia - Hispania\">Hispania</option>"
      // +"<option value=\"Antioquia - Itagüí\">Itagüí</option>"
      // +"<option value=\"Antioquia - Ituango\">Ituango</option>"
      // +"<option value=\"Antioquia - Jardín\">Jardín</option>"
      // +"<option value=\"Antioquia - Jericó\">Jericó</option>"
      // +"<option value=\"Antioquia - La Ceja\">La Ceja</option>"
      // +"<option value=\"Antioquia - La Estrella\">La Estrella</option>"
      // +"<option value=\"Antioquia - La Pintada\">La Pintada</option>"
      // +"<option value=\"Antioquia - La Unión\">La Unión</option>"
      // +"<option value=\"Antioquia - Liborina\">Liborina</option>"
      // +"<option value=\"Antioquia - Maceo\">Maceo</option>"
      // +"<option value=\"Antioquia - Marinilla\">Marinilla</option>"
      // +"<option value=\"Antioquia - Medellín\">Medellín</option>"
      // +"<option value=\"Antioquia - Montebello\">Montebello</option>"
      // +"<option value=\"Antioquia - Murindó\">Murindó</option>"
      // +"<option value=\"Antioquia - Mutatá\">Mutatá</option>"
      // +"<option value=\"Antioquia - Nariño\">Nariño</option>"
      // +"<option value=\"Antioquia - Nechí\">Nechí</option>"
      // +"<option value=\"Antioquia - Necoclí\">Necoclí</option>"
      // +"<option value=\"Antioquia - Olaya\">Olaya</option>"
      // +"<option value=\"Antioquia - Peque\">Peque</option>"
      // +"<option value=\"Antioquia - Pueblorrico\">Pueblorrico</option>"
      // +"<option value=\"Antioquia - Puerto Berrío\">Puerto Berrío</option>"
      // +"<option value=\"Antioquia - Puerto Nare\">Puerto Nare</option>"
      // +"<option value=\"Antioquia - Puerto Triunfo\">Puerto Triunfo</option>"
      // +"<option value=\"Antioquia - Remedios\">Remedios</option>"
      // +"<option value=\"Antioquia - Rionegro\">Rionegro</option>"
      // +"<option value=\"Antioquia - Sabanalarga\">Sabanalarga</option>"
      // +"<option value=\"Antioquia - Sabaneta\">Sabaneta</option>"
      // +"<option value=\"Antioquia - Salgar\">Salgar</option>"
      // +"<option value=\"Antioquia - San Andrés de Cuerquia\">San Andrés de Cuerquia</option>"
      // +"<option value=\"Antioquia - San Carlos\">San Carlos</option>"
      // +"<option value=\"Antioquia - San Francisco\">San Francisco</option>"
      // +"<option value=\"Antioquia - San Jerónimo\">San Jerónimo</option>"
      // +"<option value=\"Antioquia - San José de la Montaña\">San José de la Montaña</option>"
      // +"<option value=\"Antioquia - San Juan de Urabá\">San Juan de Urabá</option>"
      // +"<option value=\"Antioquia - San Luis\">San Luis</option>"
      // +"<option value=\"Antioquia - San Pedro de los Milagros\">San Pedro de los Milagros</option>"
      // +"<option value=\"Antioquia - San Pedro de Urabá\">San Pedro de Urabá</option>"
      // +"<option value=\"Antioquia - San Rafael\">San Rafael</option>"
      // +"<option value=\"Antioquia - San Roque\">San Roque</option>"
      // +"<option value=\"Antioquia - San Vicente\">San Vicente</option>"
      // +"<option value=\"Antioquia - Santa Bárbara\">Santa Bárbara</option>"
      // +"<option value=\"Antioquia - Santa Fe de Antioquia\">Santa Fe de Antioquia</option>"
      // +"<option value=\"Antioquia - Santa Rosa de Osos\">Santa Rosa de Osos</option>"
      // +"<option value=\"Antioquia - Santo Domingo\">Santo Domingo</option>"
      // +"<option value=\"Antioquia - Segovia\">Segovia</option>"
      // +"<option value=\"Antioquia - Sonsón\">Sonsón</option>"
      // +"<option value=\"Antioquia - Sopetrán\">Sopetrán</option>"
      // +"<option value=\"Antioquia - Támesis\">Támesis</option>"
      // +"<option value=\"Antioquia - Tarazá\">Tarazá</option>"
      // +"<option value=\"Antioquia - Tarso\">Tarso</option>"
      // +"<option value=\"Antioquia - Titiribí\">Titiribí</option>"
      // +"<option value=\"Antioquia - Toledo\">Toledo</option>"
      // +"<option value=\"Antioquia - Turbo\">Turbo</option>"
      // +"<option value=\"Antioquia - Uramita\">Uramita</option>"
      // +"<option value=\"Antioquia - Urrao\">Urrao</option>"
      // +"<option value=\"Antioquia - Valdivia\">Valdivia</option>"
      // +"<option value=\"Antioquia - Valparaíso\">Valparaíso</option>"
      // +"<option value=\"Antioquia - Vegachí\">Vegachí</option>"
      // +"<option value=\"Antioquia - Venecia\">Venecia</option>"
      // +"<option value=\"Antioquia - Vigía del Fuerte\">Vigía del Fuerte</option>"
      // +"<option value=\"Antioquia - Yalí\">Yalí</option>"
      // +"<option value=\"Antioquia - Yarumal\">Yarumal</option>"
      // +"<option value=\"Antioquia - Yolombó\">Yolombó</option>"
      // +"<option value=\"Antioquia - Yondó\">Yondó</option>"
      // +"<option value=\"Antioquia - Zaragoza\">Zaragoza</option>"
      // +"<option value=\"Arauca - Arauca\">Arauca</option>"
      // +"<option value=\"Arauca - Arauquita\">Arauquita</option>"
      // +"<option value=\"Arauca - Cravo Norte\">Cravo Norte</option>"
      // +"<option value=\"Arauca - Fortul\">Fortul</option>"
      // +"<option value=\"Arauca - Puerto Rondón\">Puerto Rondón</option>"
      // +"<option value=\"Arauca - Saravena\">Saravena</option>"
      // +"<option value=\"Arauca - Tame\">Tame</option>"
      // +"<option value=\"Atlántico - Baranoa\">Baranoa</option>"
      // +"<option value=\"Atlántico - Barranquilla\">Barranquilla</option>"
      // +"<option value=\"Atlántico - Campo de La Cruz\">Campo de La Cruz</option>"
      // +"<option value=\"Atlántico - Candelaria\">Candelaria</option>"
      // +"<option value=\"Atlántico - Galapa\">Galapa</option>"
      // +"<option value=\"Atlántico - Juan de Acosta\">Juan de Acosta</option>"
      // +"<option value=\"Atlántico - Luruaco\">Luruaco</option>"
      // +"<option value=\"Atlántico - Malambo\">Malambo</option>"
      // +"<option value=\"Atlántico - Manatí\">Manatí</option>"
      // +"<option value=\"Atlántico - Palmar de Varela\">Palmar de Varela</option>"
      // +"<option value=\"Atlántico - Piojó\">Piojó</option>"
      // +"<option value=\"Atlántico - Polonuevo\">Polonuevo</option>"
      // +"<option value=\"Atlántico - Ponedera\">Ponedera</option>"
      // +"<option value=\"Atlántico - Puerto Colombia\">Puerto Colombia</option>"
      // +"<option value=\"Atlántico - Repelón\">Repelón</option>"
      // +"<option value=\"Atlántico - Sabanagrande\">Sabanagrande</option>"
      // +"<option value=\"Atlántico - Sabanalarga\">Sabanalarga</option>"
      // +"<option value=\"Atlántico - Santa Lucía\">Santa Lucía</option>"
      // +"<option value=\"Atlántico - Santo Tomás\">Santo Tomás</option>"
      // +"<option value=\"Atlántico - Soledad\">Soledad</option>"
      // +"<option value=\"Atlántico - Suán\">Suán</option>"
      // +"<option value=\"Atlántico - Tubará\">Tubará</option>"
      // +"<option value=\"Atlántico - Usiacurí\">Usiacurí</option>"
      // +"<option value=\"Bolívar - Achí\">Achí</option>"
      // +"<option value=\"Bolívar - Altos del Rosario\">Altos del Rosario</option>"
      // +"<option value=\"Bolívar - Arenal\">Arenal</option>"
      // +"<option value=\"Bolívar - Arjona\">Arjona</option>"
      // +"<option value=\"Bolívar - Arroyohondo\">Arroyohondo</option>"
      // +"<option value=\"Bolívar - Barranco de Loba\">Barranco de Loba</option>"
      // +"<option value=\"Bolívar - Brazuelo de Papayal\">Brazuelo de Papayal</option>"
      // +"<option value=\"Bolívar - Calamar\">Calamar</option>"
      // +"<option value=\"Bolívar - Cantagallo\">Cantagallo</option>"
      // +"<option value=\"Bolívar - Cartagena de Indias\">Cartagena de Indias</option>"
      // +"<option value=\"Bolívar - Cicuco\">Cicuco</option>"
      // +"<option value=\"Bolívar - Clemencia\">Clemencia</option>"
      // +"<option value=\"Bolívar - Córdoba\">Córdoba</option>"
      // +"<option value=\"Bolívar - El Carmen de Bolívar\">El Carmen de Bolívar</option>"
      // +"<option value=\"Bolívar - El Guamo\">El Guamo</option>"
      // +"<option value=\"Bolívar - El Peñón\">El Peñón</option>"
      // +"<option value=\"Bolívar - Hatillo de Loba\">Hatillo de Loba</option>"
      // +"<option value=\"Bolívar - Magangué\">Magangué</option>"
      // +"<option value=\"Bolívar - Mahates\">Mahates</option>"
      // +"<option value=\"Bolívar - Margarita\">Margarita</option>"
      // +"<option value=\"Bolívar - María La Baja\">María La Baja</option>"
      // +"<option value=\"Bolívar - Montecristo\">Montecristo</option>"
      // +"<option value=\"Bolívar - Morales\">Morales</option>"
      // +"<option value=\"Bolívar - Norosí\">Norosí</option>"
      // +"<option value=\"Bolívar - Pinillos\">Pinillos</option>"
      // +"<option value=\"Bolívar - Regidor\">Regidor</option>"
      // +"<option value=\"Bolívar - Río Viejo\">Río Viejo</option>"
      // +"<option value=\"Bolívar - San Cristóbal\">San Cristóbal</option>"
      // +"<option value=\"Bolívar - San Estanislao\">San Estanislao</option>"
      // +"<option value=\"Bolívar - San Fernando\">San Fernando</option>"
      // +"<option value=\"Bolívar - San Jacinto\">San Jacinto</option>"
      // +"<option value=\"Bolívar - San Jacinto del Cauca\">San Jacinto del Cauca</option>"
      // +"<option value=\"Bolívar - San Juan Nepomuceno\">San Juan Nepomuceno</option>"
      // +"<option value=\"Bolívar - San Martín de Loba\">San Martín de Loba</option>"
      // +"<option value=\"Bolívar - San Pablo\">San Pablo</option>"
      // +"<option value=\"Bolívar - Santa Catalina\">Santa Catalina</option>"
      // +"<option value=\"Bolívar - Santa Cruz de Mompox\">Santa Cruz de Mompox</option>"
      // +"<option value=\"Bolívar - Santa Rosa de Lima\">Santa Rosa de Lima</option>"
      // +"<option value=\"Bolívar - Santa Rosa del Sur\">Santa Rosa del Sur</option>"
      // +"<option value=\"Bolívar - Simití\">Simití</option>"
      // +"<option value=\"Bolívar - Soplaviento\">Soplaviento</option>"
      // +"<option value=\"Bolívar - Talaigua Nuevo\">Talaigua Nuevo</option>"
      // +"<option value=\"Bolívar - Tiquisio\">Tiquisio</option>"
      // +"<option value=\"Bolívar - Turbaco\">Turbaco</option>"
      // +"<option value=\"Bolívar - Turbaná\">Turbaná</option>"
      // +"<option value=\"Bolívar - Villanueva\">Villanueva</option>"
      // +"<option value=\"Bolívar - Zambrano\">Zambrano</option>"
      // +"<option value=\"Boyacá - Almeida\">Almeida</option>"
      // +"<option value=\"Boyacá - Aquitania\">Aquitania</option>"
      // +"<option value=\"Boyacá - Arcabuco\">Arcabuco</option>"
      // +"<option value=\"Boyacá - Belén\">Belén</option>"
      // +"<option value=\"Boyacá - Berbeo\">Berbeo</option>"
      // +"<option value=\"Boyacá - Betéitiva\">Betéitiva</option>"
      // +"<option value=\"Boyacá - Boavita\">Boavita</option>"
      // +"<option value=\"Boyacá - Boyacá\">Boyacá</option>"
      // +"<option value=\"Boyacá - Briceño\">Briceño</option>"
      // +"<option value=\"Boyacá - Buenavista\">Buenavista</option>"
      // +"<option value=\"Boyacá - Busbanzá\">Busbanzá</option>"
      // +"<option value=\"Boyacá - Caldas\">Caldas</option>"
      // +"<option value=\"Boyacá - Campohermoso\">Campohermoso</option>"
      // +"<option value=\"Boyacá - Cerinza\">Cerinza</option>"
      // +"<option value=\"Boyacá - Chinavita\">Chinavita</option>"
      // +"<option value=\"Boyacá - Chiquinquirá\">Chiquinquirá</option>"
      // +"<option value=\"Boyacá - Chíquiza\">Chíquiza</option>"
      // +"<option value=\"Boyacá - Chiscas\">Chiscas</option>"
      // +"<option value=\"Boyacá - Chita\">Chita</option>"
      // +"<option value=\"Boyacá - Chitaraque\">Chitaraque</option>"
      // +"<option value=\"Boyacá - Chivatá\">Chivatá</option>"
      // +"<option value=\"Boyacá - Chivor\">Chivor</option>"
      // +"<option value=\"Boyacá - Ciénega\">Ciénega</option>"
      // +"<option value=\"Boyacá - Cómbita\">Cómbita</option>"
      // +"<option value=\"Boyacá - Coper\">Coper</option>"
      // +"<option value=\"Boyacá - Corrales\">Corrales</option>"
      // +"<option value=\"Boyacá - Covarachía\">Covarachía</option>"
      // +"<option value=\"Boyacá - Cubará\">Cubará</option>"
      // +"<option value=\"Boyacá - Cucaita\">Cucaita</option>"
      // +"<option value=\"Boyacá - Cuítiva\">Cuítiva</option>"
      // +"<option value=\"Boyacá - Duitama\">Duitama</option>"
      // +"<option value=\"Boyacá - El Cocuy\">El Cocuy</option>"
      // +"<option value=\"Boyacá - El Espino\">El Espino</option>"
      // +"<option value=\"Boyacá - Firavitoba\">Firavitoba</option>"
      // +"<option value=\"Boyacá - Floresta\">Floresta</option>"
      // +"<option value=\"Boyacá - Gachantivá\">Gachantivá</option>"
      // +"<option value=\"Boyacá - Gámeza\">Gámeza</option>"
      // +"<option value=\"Boyacá - Garagoa\">Garagoa</option>"
      // +"<option value=\"Boyacá - Guacamayas\">Guacamayas</option>"
      // +"<option value=\"Boyacá - Guateque\">Guateque</option>"
      // +"<option value=\"Boyacá - Guayatá\">Guayatá</option>"
      // +"<option value=\"Boyacá - Güicán\">Güicán</option>"
      // +"<option value=\"Boyacá - Iza\">Iza</option>"
      // +"<option value=\"Boyacá - Jenesano\">Jenesano</option>"
      // +"<option value=\"Boyacá - Jericó\">Jericó</option>"
      // +"<option value=\"Boyacá - La Capilla\">La Capilla</option>"
      // +"<option value=\"Boyacá - La Uvita\">La Uvita</option>"
      // +"<option value=\"Boyacá - La Victoria\">La Victoria</option>"
      // +"<option value=\"Boyacá - Labranzagrande\">Labranzagrande</option>"
      // +"<option value=\"Boyacá - Macanal\">Macanal</option>"
      // +"<option value=\"Boyacá - Maripí\">Maripí</option>"
      // +"<option value=\"Boyacá - Miraflores\">Miraflores</option>"
      // +"<option value=\"Boyacá - Mongua\">Mongua</option>"
      // +"<option value=\"Boyacá - Monguí\">Monguí</option>"
      // +"<option value=\"Boyacá - Moniquirá\">Moniquirá</option>"
      // +"<option value=\"Boyacá - Motavita\">Motavita</option>"
      // +"<option value=\"Boyacá - Muzo\">Muzo</option>"
      // +"<option value=\"Boyacá - Nobsa\">Nobsa</option>"
      // +"<option value=\"Boyacá - Nuevo Colón\">Nuevo Colón</option>"
      // +"<option value=\"Boyacá - Oicatá\">Oicatá</option>"
      // +"<option value=\"Boyacá - Otanche\">Otanche</option>"
      // +"<option value=\"Boyacá - Pachavita\">Pachavita</option>"
      // +"<option value=\"Boyacá - Páez\">Páez</option>"
      // +"<option value=\"Boyacá - Paipa\">Paipa</option>"
      // +"<option value=\"Boyacá - Pajarito\">Pajarito</option>"
      // +"<option value=\"Boyacá - Panqueba\">Panqueba</option>"
      // +"<option value=\"Boyacá - Pauna\">Pauna</option>"
      // +"<option value=\"Boyacá - Paya\">Paya</option>"
      // +"<option value=\"Boyacá - Paz de Río\">Paz de Río</option>"
      // +"<option value=\"Boyacá - Pesca\">Pesca</option>"
      // +"<option value=\"Boyacá - Pisba\">Pisba</option>"
      // +"<option value=\"Boyacá - Puerto Boyacá\">Puerto Boyacá</option>"
      // +"<option value=\"Boyacá - Quípama\">Quípama</option>"
      // +"<option value=\"Boyacá - Ramiriquí\">Ramiriquí</option>"
      // +"<option value=\"Boyacá - Ráquira\">Ráquira</option>"
      // +"<option value=\"Boyacá - Rondón\">Rondón</option>"
      // +"<option value=\"Boyacá - Saboyá\">Saboyá</option>"
      // +"<option value=\"Boyacá - Sáchica\">Sáchica</option>"
      // +"<option value=\"Boyacá - Samacá\">Samacá</option>"
      // +"<option value=\"Boyacá - San Eduardo\">San Eduardo</option>"
      // +"<option value=\"Boyacá - San José de Pare\">San José de Pare</option>"
      // +"<option value=\"Boyacá - San Luis de Gaceno\">San Luis de Gaceno</option>"
      // +"<option value=\"Boyacá - San Mateo\">San Mateo</option>"
      // +"<option value=\"Boyacá - San Miguel de Sema\">San Miguel de Sema</option>"
      // +"<option value=\"Boyacá - San Pablo de Borbur\">San Pablo de Borbur</option>"
      // +"<option value=\"Boyacá - Santa María\">Santa María</option>"
      // +"<option value=\"Boyacá - Santa Rosa de Viterbo\">Santa Rosa de Viterbo</option>"
      // +"<option value=\"Boyacá - Santa Sofía\">Santa Sofía</option>"
      // +"<option value=\"Boyacá - Santana\">Santana</option>"
      // +"<option value=\"Boyacá - Sativanorte\">Sativanorte</option>"
      // +"<option value=\"Boyacá - Sativasur\">Sativasur</option>"
      // +"<option value=\"Boyacá - Siachoque\">Siachoque</option>"
      // +"<option value=\"Boyacá - Soatá\">Soatá</option>"
      // +"<option value=\"Boyacá - Socha\">Socha</option>"
      // +"<option value=\"Boyacá - Socotá\">Socotá</option>"
      // +"<option value=\"Boyacá - Sogamoso\">Sogamoso</option>"
      // +"<option value=\"Boyacá - Somondoco\">Somondoco</option>"
      // +"<option value=\"Boyacá - Sora\">Sora</option>"
      // +"<option value=\"Boyacá - Soracá\">Soracá</option>"
      // +"<option value=\"Boyacá - Sotaquirá\">Sotaquirá</option>"
      // +"<option value=\"Boyacá - Susacón\">Susacón</option>"
      // +"<option value=\"Boyacá - Sutamarchán\">Sutamarchán</option>"
      // +"<option value=\"Boyacá - Sutatenza\">Sutatenza</option>"
      // +"<option value=\"Boyacá - Tasco\">Tasco</option>"
      // +"<option value=\"Boyacá - Tenza\">Tenza</option>"
      // +"<option value=\"Boyacá - Tibaná\">Tibaná</option>"
      // +"<option value=\"Boyacá - Tibasosa\">Tibasosa</option>"
      // +"<option value=\"Boyacá - Tinjacá\">Tinjacá</option>"
      // +"<option value=\"Boyacá - Tipacoque\">Tipacoque</option>"
      // +"<option value=\"Boyacá - Toca\">Toca</option>"
      // +"<option value=\"Boyacá - Togüí\">Togüí</option>"
      // +"<option value=\"Boyacá - Tópaga\">Tópaga</option>"
      // +"<option value=\"Boyacá - Tota\">Tota</option>"
      // +"<option value=\"Boyacá - Tunja\">Tunja</option>"
      // +"<option value=\"Boyacá - Tunungua\">Tunungua</option>"
      // +"<option value=\"Boyacá - Turmequé\">Turmequé</option>"
      // +"<option value=\"Boyacá - Tuta\">Tuta</option>"
      // +"<option value=\"Boyacá - Tutazá\">Tutazá</option>"
      // +"<option value=\"Boyacá - Úmbita\">Úmbita</option>"
      // +"<option value=\"Boyacá - Ventaquemada\">Ventaquemada</option>"
      // +"<option value=\"Boyacá - Villa de Leyva\">Villa de Leyva</option>"
      // +"<option value=\"Boyacá - Viracachá\">Viracachá</option>"
      // +"<option value=\"Boyacá - Zetaquira\">Zetaquira</option>"
      // +"<option value=\"Caldas - Aguadas\">Aguadas</option>"
      // +"<option value=\"Caldas - Anserma\">Anserma</option>"
      // +"<option value=\"Caldas - Aranzazu\">Aranzazu</option>"
      // +"<option value=\"Caldas - Belalcázar\">Belalcázar</option>"
      // +"<option value=\"Caldas - Chinchiná\">Chinchiná</option>"
      // +"<option value=\"Caldas - Filadelfia\">Filadelfia</option>"
      // +"<option value=\"Caldas - La Dorada\">La Dorada</option>"
      // +"<option value=\"Caldas - La Merced\">La Merced</option>"
      // +"<option value=\"Caldas - Manizales\">Manizales</option>"
      // +"<option value=\"Caldas - Manzanares\">Manzanares</option>"
      // +"<option value=\"Caldas - Marmato\">Marmato</option>"
      // +"<option value=\"Caldas - Marquetalia\">Marquetalia</option>"
      // +"<option value=\"Caldas - Marulanda\">Marulanda</option>"
      // +"<option value=\"Caldas - Neira\">Neira</option>"
      // +"<option value=\"Caldas - Norcasia\">Norcasia</option>"
      // +"<option value=\"Caldas - Pácora\">Pácora</option>"
      // +"<option value=\"Caldas - Palestina\">Palestina</option>"
      // +"<option value=\"Caldas - Pensilvania\">Pensilvania</option>"
      // +"<option value=\"Caldas - Riosucio\">Riosucio</option>"
      // +"<option value=\"Caldas - Risaralda\">Risaralda</option>"
      // +"<option value=\"Caldas - Salamina\">Salamina</option>"
      // +"<option value=\"Caldas - Samaná\">Samaná</option>"
      // +"<option value=\"Caldas - San José\">San José</option>"
      // +"<option value=\"Caldas - Supía\">Supía</option>"
      // +"<option value=\"Caldas - Victoria\">Victoria</option>"
      // +"<option value=\"Caldas - Villamaría\">Villamaría</option>"
      // +"<option value=\"Caldas - Viterbo\">Viterbo</option>"
      // +"<option value=\"Caquetá - Albania\">Albania</option>"
      // +"<option value=\"Caquetá - Belén de los Andaquies\">Belén de los Andaquies</option>"
      // +"<option value=\"Caquetá - Cartagena del Chairá\">Cartagena del Chairá</option>"
      // +"<option value=\"Caquetá - Curillo\">Curillo</option>"
      // +"<option value=\"Caquetá - El Doncello\">El Doncello</option>"
      // +"<option value=\"Caquetá - El Paujil\">El Paujil</option>"
      // +"<option value=\"Caquetá - Florencia\">Florencia</option>"
      // +"<option value=\"Caquetá - La Montañita\">La Montañita</option>"
      // +"<option value=\"Caquetá - Morelia\">Morelia</option>"
      // +"<option value=\"Caquetá - Puerto Milán\">Puerto Milán</option>"
      // +"<option value=\"Caquetá - Puerto Rico\">Puerto Rico</option>"
      // +"<option value=\"Caquetá - San José del Fragua\">San José del Fragua</option>"
      // +"<option value=\"Caquetá - San Vicente del Caguán\">San Vicente del Caguán</option>"
      // +"<option value=\"Caquetá - Solano\">Solano</option>"
      // +"<option value=\"Caquetá - Solita\">Solita</option>"
      // +"<option value=\"Caquetá - Valparaíso\">Valparaíso</option>"
      // +"<option value=\"Casanare - Aguazul\">Aguazul</option>"
      // +"<option value=\"Casanare - Chámeza\">Chámeza</option>"
      // +"<option value=\"Casanare - Hato Corozal\">Hato Corozal</option>"
      // +"<option value=\"Casanare - La Salina\">La Salina</option>"
      // +"<option value=\"Casanare - Maní\">Maní</option>"
      // +"<option value=\"Casanare - Monterrey\">Monterrey</option>"
      // +"<option value=\"Casanare - Nunchía\">Nunchía</option>"
      // +"<option value=\"Casanare - Orocué\">Orocué</option>"
      // +"<option value=\"Casanare - Paz de Ariporo\">Paz de Ariporo</option>"
      // +"<option value=\"Casanare - Pore\">Pore</option>"
      // +"<option value=\"Casanare - Recetor\">Recetor</option>"
      // +"<option value=\"Casanare - Sabanalarga\">Sabanalarga</option>"
      // +"<option value=\"Casanare - Sácama\">Sácama</option>"
      // +"<option value=\"Casanare - San Luis de Palenque\">San Luis de Palenque</option>"
      // +"<option value=\"Casanare - Támara\">Támara</option>"
      // +"<option value=\"Casanare - Tauramena\">Tauramena</option>"
      // +"<option value=\"Casanare - Trinidad\">Trinidad</option>"
      // +"<option value=\"Casanare - Villanueva\">Villanueva</option>"
      // +"<option value=\"Casanare - Yopal\">Yopal</option>"
      // +"<option value=\"Cauca - Almaguer\">Almaguer</option>"
      // +"<option value=\"Cauca - Argelia\">Argelia</option>"
      // +"<option value=\"Cauca - Balboa\">Balboa</option>"
      // +"<option value=\"Cauca - Bolívar\">Bolívar</option>"
      // +"<option value=\"Cauca - Buenos Aires\">Buenos Aires</option>"
      // +"<option value=\"Cauca - Cajibío\">Cajibío</option>"
      // +"<option value=\"Cauca - Caldono\">Caldono</option>"
      // +"<option value=\"Cauca - Caloto\">Caloto</option>"
      // +"<option value=\"Cauca - Corinto\">Corinto</option>"
      // +"<option value=\"Cauca - El Tambo\">El Tambo</option>"
      // +"<option value=\"Cauca - Florencia\">Florencia</option>"
      // +"<option value=\"Cauca - Guachené\">Guachené</option>"
      // +"<option value=\"Cauca - Guapí\">Guapí</option>"
      // +"<option value=\"Cauca - Inzá\">Inzá</option>"
      // +"<option value=\"Cauca - Jambaló\">Jambaló</option>"
      // +"<option value=\"Cauca - La Sierra\">La Sierra</option>"
      // +"<option value=\"Cauca - La Vega\">La Vega</option>"
      // +"<option value=\"Cauca - López de Micay\">López de Micay</option>"
      // +"<option value=\"Cauca - Mercaderes\">Mercaderes</option>"
      // +"<option value=\"Cauca - Miranda\">Miranda</option>"
      // +"<option value=\"Cauca - Morales\">Morales</option>"
      // +"<option value=\"Cauca - Padilla\">Padilla</option>"
      // +"<option value=\"Cauca - Páez\">Páez</option>"
      // +"<option value=\"Cauca - Patía\">Patía</option>"
      // +"<option value=\"Cauca - Piamonte\">Piamonte</option>"
      // +"<option value=\"Cauca - Piendamó\">Piendamó</option>"
      // +"<option value=\"Cauca - Popayán\">Popayán</option>"
      // +"<option value=\"Cauca - Puerto Tejada\">Puerto Tejada</option>"
      // +"<option value=\"Cauca - Puracé\">Puracé</option>"
      // +"<option value=\"Cauca - Rosas\">Rosas</option>"
      // +"<option value=\"Cauca - San Sebastián\">San Sebastián</option>"
      // +"<option value=\"Cauca - Santa Rosa\">Santa Rosa</option>"
      // +"<option value=\"Cauca - Santander de Quilichao\">Santander de Quilichao</option>"
      // +"<option value=\"Cauca - Silvia\">Silvia</option>"
      // +"<option value=\"Cauca - Sotará\">Sotará</option>"
      // +"<option value=\"Cauca - Suárez\">Suárez</option>"
      // +"<option value=\"Cauca - Sucre\">Sucre</option>"
      // +"<option value=\"Cauca - Timbío\">Timbío</option>"
      // +"<option value=\"Cauca - Timbiquí\">Timbiquí</option>"
      // +"<option value=\"Cauca - Toribío\">Toribío</option>"
      // +"<option value=\"Cauca - Totoró\">Totoró</option>"
      // +"<option value=\"Cauca - Villa Rica\">Villa Rica</option>"
      // +"<option value=\"Cesar - Aguachica\">Aguachica</option>"
      // +"<option value=\"Cesar - Agustín Codazzi\">Agustín Codazzi</option>"
      // +"<option value=\"Cesar - Astrea\">Astrea</option>"
      // +"<option value=\"Cesar - Becerril\">Becerril</option>"
      // +"<option value=\"Cesar - Bosconia\">Bosconia</option>"
      // +"<option value=\"Cesar - Chimichagua\">Chimichagua</option>"
      // +"<option value=\"Cesar - Chiriguaná\">Chiriguaná</option>"
      // +"<option value=\"Cesar - Curumaní\">Curumaní</option>"
      // +"<option value=\"Cesar - El Copey\">El Copey</option>"
      // +"<option value=\"Cesar - El Paso\">El Paso</option>"
      // +"<option value=\"Cesar - Gamarra\">Gamarra</option>"
      // +"<option value=\"Cesar - González\">González</option>"
      // +"<option value=\"Cesar - La Gloria\">La Gloria</option>"
      // +"<option value=\"Cesar - La Jagua de Ibirico\">La Jagua de Ibirico</option>"
      // +"<option value=\"Cesar - La Paz\">La Paz</option>"
      // +"<option value=\"Cesar - Manaure Balcón del Cesar\">Manaure Balcón del Cesar</option>"
      // +"<option value=\"Cesar - Pailitas\">Pailitas</option>"
      // +"<option value=\"Cesar - Pelaya\">Pelaya</option>"
      // +"<option value=\"Cesar - Pueblo Bello\">Pueblo Bello</option>"
      // +"<option value=\"Cesar - Río de Oro\">Río de Oro</option>"
      // +"<option value=\"Cesar - San Alberto\">San Alberto</option>"
      // +"<option value=\"Cesar - San Diego\">San Diego</option>"
      // +"<option value=\"Cesar - San Martín\">San Martín</option>"
      // +"<option value=\"Cesar - Tamalameque\">Tamalameque</option>"
      // +"<option value=\"Cesar - Valledupar\">Valledupar</option>"
      // +"<option value=\"Chocó - Acandí\">Acandí</option>"
      // +"<option value=\"Chocó - Alto Baudó\">Alto Baudó</option>"
      // +"<option value=\"Chocó - Bagadó\">Bagadó</option>"
      // +"<option value=\"Chocó - Bahía Solano\">Bahía Solano</option>"
      // +"<option value=\"Chocó - Bajo Baudó\">Bajo Baudó</option>"
      // +"<option value=\"Chocó - Bojayá\">Bojayá</option>"
      // +"<option value=\"Chocó - Cantón de San Pablo\">Cantón de San Pablo</option>"
      // +"<option value=\"Chocó - Cértegui\">Cértegui</option>"
      // +"<option value=\"Chocó - Condoto\">Condoto</option>"
      // +"<option value=\"Chocó - El Atrato\">El Atrato</option>"
      // +"<option value=\"Chocó - El Carmen de Atrato\">El Carmen de Atrato</option>"
      // +"<option value=\"Chocó - El Carmen del Darién\">El Carmen del Darién</option>"
      // +"<option value=\"Chocó - El Litoral de San Juan\">El Litoral de San Juan</option>"
      // +"<option value=\"Chocó - Istmina\">Istmina</option>"
      // +"<option value=\"Chocó - Juradó\">Juradó</option>"
      // +"<option value=\"Chocó - Lloró\">Lloró</option>"
      // +"<option value=\"Chocó - Medio Atrato\">Medio Atrato</option>"
      // +"<option value=\"Chocó - Medio Baudó\">Medio Baudó</option>"
      // +"<option value=\"Chocó - Medio San Juan\">Medio San Juan</option>"
      // +"<option value=\"Chocó - Nóvita\">Nóvita</option>"
      // +"<option value=\"Chocó - Nuquí\">Nuquí</option>"
      // +"<option value=\"Chocó - Quibdó\">Quibdó</option>"
      // +"<option value=\"Chocó - Río Iró\">Río Iró</option>"
      // +"<option value=\"Chocó - Río Quito\">Río Quito</option>"
      // +"<option value=\"Chocó - Riosucio\">Riosucio</option>"
      // +"<option value=\"Chocó - San José del Palmar\">San José del Palmar</option>"
      // +"<option value=\"Chocó - Sipí\">Sipí</option>"
      // +"<option value=\"Chocó - Tadó\">Tadó</option>"
      // +"<option value=\"Chocó - Unguía\">Unguía</option>"
      // +"<option value=\"Chocó - Unión Panamericana\">Unión Panamericana</option>"
      // +"<option value=\"Córdoba - Ayapel\">Ayapel</option>"
      // +"<option value=\"Córdoba - Buenavista\">Buenavista</option>"
      // +"<option value=\"Córdoba - Canalete\">Canalete</option>"
      // +"<option value=\"Córdoba - Cereté\">Cereté</option>"
      // +"<option value=\"Córdoba - Chimá\">Chimá</option>"
      // +"<option value=\"Córdoba - Chinú\">Chinú</option>"
      // +"<option value=\"Córdoba - Ciénaga de Oro\">Ciénaga de Oro</option>"
      // +"<option value=\"Córdoba - Cotorra\">Cotorra</option>"
      // +"<option value=\"Córdoba - La Apartada\">La Apartada</option>"
      // +"<option value=\"Córdoba - Los Córdobas\">Los Córdobas</option>"
      // +"<option value=\"Córdoba - Momil\">Momil</option>"
      // +"<option value=\"Córdoba - Montelíbano\">Montelíbano</option>"
      // +"<option value=\"Córdoba - Montería\">Montería</option>"
      // +"<option value=\"Córdoba - Moñitos\">Moñitos</option>"
      // +"<option value=\"Córdoba - Planeta Rica\">Planeta Rica</option>"
      // +"<option value=\"Córdoba - Pueblo Nuevo\">Pueblo Nuevo</option>"
      // +"<option value=\"Córdoba - Puerto Escondido\">Puerto Escondido</option>"
      // +"<option value=\"Córdoba - Puerto Libertador\">Puerto Libertador</option>"
      // +"<option value=\"Córdoba - Purísima\">Purísima</option>"
      // +"<option value=\"Córdoba - Sahagún\">Sahagún</option>"
      // +"<option value=\"Córdoba - San Andrés de Sotavento\">San Andrés de Sotavento</option>"
      // +"<option value=\"Córdoba - San Antero\">San Antero</option>"
      // +"<option value=\"Córdoba - San Bernardo del Viento\">San Bernardo del Viento</option>"
      // +"<option value=\"Córdoba - San Carlos\">San Carlos</option>"
      // +"<option value=\"Córdoba - San José de Uré\">San José de Uré</option>"
      // +"<option value=\"Córdoba - San Pelayo\">San Pelayo</option>"
      // +"<option value=\"Córdoba - Santa Cruz de Lorica\">Santa Cruz de Lorica</option>"
      // +"<option value=\"Córdoba - Tierralta\">Tierralta</option>"
      // +"<option value=\"Córdoba - Tuchín\">Tuchín</option>"
      // +"<option value=\"Córdoba - Valencia\">Valencia</option>"
      // +"<option value=\"Cundinamarca - Agua de Dios\">Agua de Dios</option>"
      // +"<option value=\"Cundinamarca - Albán\">Albán</option>"
      // +"<option value=\"Cundinamarca - Anapoima\">Anapoima</option>"
      // +"<option value=\"Cundinamarca - Anolaima\">Anolaima</option>"
      // +"<option value=\"Cundinamarca - Apulo\">Apulo</option>"
      // +"<option value=\"Cundinamarca - Arbelaéz\">Arbelaéz</option>"
      // +"<option value=\"Cundinamarca - Beltrán\">Beltrán</option>"
      // +"<option value=\"Cundinamarca - Bituima\">Bituima</option>"
      // +"<option value=\"Cundinamarca - Bogotá\">Bogotá</option>"
      // +"<option value=\"Cundinamarca - Bojacá\">Bojacá</option>"
      // +"<option value=\"Cundinamarca - Cabrera\">Cabrera</option>"
      // +"<option value=\"Cundinamarca - Cachipay\">Cachipay</option>"
      // +"<option value=\"Cundinamarca - Cajicá\">Cajicá</option>"
      // +"<option value=\"Cundinamarca - Caparrapí\">Caparrapí</option>"
      // +"<option value=\"Cundinamarca - Cáqueza\">Cáqueza</option>"
      // +"<option value=\"Cundinamarca - Carmen de Carupa\">Carmen de Carupa</option>"
      // +"<option value=\"Cundinamarca - Chaguaní\">Chaguaní</option>"
      // +"<option value=\"Cundinamarca - Chía\">Chía</option>"
      // +"<option value=\"Cundinamarca - Chipaque\">Chipaque</option>"
      // +"<option value=\"Cundinamarca - Choachí\">Choachí</option>"
      // +"<option value=\"Cundinamarca - Chocontá\">Chocontá</option>"
      // +"<option value=\"Cundinamarca - Cogua\">Cogua</option>"
      // +"<option value=\"Cundinamarca - Cota\">Cota</option>"
      // +"<option value=\"Cundinamarca - Cucunubá\">Cucunubá</option>"
      // +"<option value=\"Cundinamarca - El Colegio\">El Colegio</option>"
      // +"<option value=\"Cundinamarca - El Peñón\">El Peñón</option>"
      // +"<option value=\"Cundinamarca - El Rosal\">El Rosal</option>"
      // +"<option value=\"Cundinamarca - Facatativá\">Facatativá</option>"
      // +"<option value=\"Cundinamarca - Fómeque\">Fómeque</option>"
      // +"<option value=\"Cundinamarca - Fosca\">Fosca</option>"
      // +"<option value=\"Cundinamarca - Funza\">Funza</option>"
      // +"<option value=\"Cundinamarca - Fúquene\">Fúquene</option>"
      // +"<option value=\"Cundinamarca - Fusagasugá\">Fusagasugá</option>"
      // +"<option value=\"Cundinamarca - Gachalá\">Gachalá</option>"
      // +"<option value=\"Cundinamarca - Gachancipá\">Gachancipá</option>"
      // +"<option value=\"Cundinamarca - Gachetá\">Gachetá</option>"
      // +"<option value=\"Cundinamarca - Gama\">Gama</option>"
      // +"<option value=\"Cundinamarca - Girardot\">Girardot</option>"
      // +"<option value=\"Cundinamarca - Granada\">Granada</option>"
      // +"<option value=\"Cundinamarca - Guachetá\">Guachetá</option>"
      // +"<option value=\"Cundinamarca - Guaduas\">Guaduas</option>"
      // +"<option value=\"Cundinamarca - Guasca\">Guasca</option>"
      // +"<option value=\"Cundinamarca - Guataquí\">Guataquí</option>"
      // +"<option value=\"Cundinamarca - Guatavita\">Guatavita</option>"
      // +"<option value=\"Cundinamarca - Guayabal de Síquima\">Guayabal de Síquima</option>"
      // +"<option value=\"Cundinamarca - Guayabetal\">Guayabetal</option>"
      // +"<option value=\"Cundinamarca - Gutiérrez\">Gutiérrez</option>"
      // +"<option value=\"Cundinamarca - Jerusalén\">Jerusalén</option>"
      // +"<option value=\"Cundinamarca - Junín\">Junín</option>"
      // +"<option value=\"Cundinamarca - La Calera\">La Calera</option>"
      // +"<option value=\"Cundinamarca - La Mesa\">La Mesa</option>"
      // +"<option value=\"Cundinamarca - La Palma\">La Palma</option>"
      // +"<option value=\"Cundinamarca - La Peña\">La Peña</option>"
      // +"<option value=\"Cundinamarca - La Vega\">La Vega</option>"
      // +"<option value=\"Cundinamarca - Lenguazaque\">Lenguazaque</option>"
      // +"<option value=\"Cundinamarca - Machetá\">Machetá</option>"
      // +"<option value=\"Cundinamarca - Madrid\">Madrid</option>"
      // +"<option value=\"Cundinamarca - Manta\">Manta</option>"
      // +"<option value=\"Cundinamarca - Medina\">Medina</option>"
      // +"<option value=\"Cundinamarca - Mosquera\">Mosquera</option>"
      // +"<option value=\"Cundinamarca - Nariño\">Nariño</option>"
      // +"<option value=\"Cundinamarca - Nemocón\">Nemocón</option>"
      // +"<option value=\"Cundinamarca - Nilo\">Nilo</option>"
      // +"<option value=\"Cundinamarca - Nimaima\">Nimaima</option>"
      // +"<option value=\"Cundinamarca - Nocaima\">Nocaima</option>"
      // +"<option value=\"Cundinamarca - Pacho\">Pacho</option>"
      // +"<option value=\"Cundinamarca - Paime\">Paime</option>"
      // +"<option value=\"Cundinamarca - Pandi\">Pandi</option>"
      // +"<option value=\"Cundinamarca - Paratebueno\">Paratebueno</option>"
      // +"<option value=\"Cundinamarca - Pasca\">Pasca</option>"
      // +"<option value=\"Cundinamarca - Puerto Salgar\">Puerto Salgar</option>"
      // +"<option value=\"Cundinamarca - Pulí\">Pulí</option>"
      // +"<option value=\"Cundinamarca - Quebradanegra\">Quebradanegra</option>"
      // +"<option value=\"Cundinamarca - Quetame\">Quetame</option>"
      // +"<option value=\"Cundinamarca - Quipile\">Quipile</option>"
      // +"<option value=\"Cundinamarca - Ricaurte\">Ricaurte</option>"
      // +"<option value=\"Cundinamarca - San Antonio del Tequendama\">San Antonio del Tequendama</option>"
      // +"<option value=\"Cundinamarca - San Bernardo\">San Bernardo</option>"
      // +"<option value=\"Cundinamarca - San Cayetano\">San Cayetano</option>"
      // +"<option value=\"Cundinamarca - San Francisco\">San Francisco</option>"
      // +"<option value=\"Cundinamarca - San Juan de Rioseco\">San Juan de Rioseco</option>"
      // +"<option value=\"Cundinamarca - Sasaima\">Sasaima</option>"
      // +"<option value=\"Cundinamarca - Sesquilé\">Sesquilé</option>"
      // +"<option value=\"Cundinamarca - Sibaté\">Sibaté</option>"
      // +"<option value=\"Cundinamarca - Silvania\">Silvania</option>"
      // +"<option value=\"Cundinamarca - Simijaca\">Simijaca</option>"
      // +"<option value=\"Cundinamarca - Soacha\">Soacha</option>"
      // +"<option value=\"Cundinamarca - Sopó\">Sopó</option>"
      // +"<option value=\"Cundinamarca - Subachoque\">Subachoque</option>"
      // +"<option value=\"Cundinamarca - Suesca\">Suesca</option>"
      // +"<option value=\"Cundinamarca - Supatá\">Supatá</option>"
      // +"<option value=\"Cundinamarca - Susa\">Susa</option>"
      // +"<option value=\"Cundinamarca - Sutatausa\">Sutatausa</option>"
      // +"<option value=\"Cundinamarca - Tabio\">Tabio</option>"
      // +"<option value=\"Cundinamarca - Tausa\">Tausa</option>"
      // +"<option value=\"Cundinamarca - Tena\">Tena</option>"
      // +"<option value=\"Cundinamarca - Tenjo\">Tenjo</option>"
      // +"<option value=\"Cundinamarca - Tibacuy\">Tibacuy</option>"
      // +"<option value=\"Cundinamarca - Tibirita\">Tibirita</option>"
      // +"<option value=\"Cundinamarca - Tocaima\">Tocaima</option>"
      // +"<option value=\"Cundinamarca - Tocancipá\">Tocancipá</option>"
      // +"<option value=\"Cundinamarca - Topaipí\">Topaipí</option>"
      // +"<option value=\"Cundinamarca - Ubalá\">Ubalá</option>"
      // +"<option value=\"Cundinamarca - Ubaque\">Ubaque</option>"
      // +"<option value=\"Cundinamarca - Ubaté\">Ubaté</option>"
      // +"<option value=\"Cundinamarca - Une\">Une</option>"
      // +"<option value=\"Cundinamarca - Útica\">Útica</option>"
      // +"<option value=\"Cundinamarca - Venecia\">Venecia</option>"
      // +"<option value=\"Cundinamarca - Vergara\">Vergara</option>"
      // +"<option value=\"Cundinamarca - Vianí\">Vianí</option>"
      // +"<option value=\"Cundinamarca - Villagómez\">Villagómez</option>"
      // +"<option value=\"Cundinamarca - Villapinzón\">Villapinzón</option>"
      // +"<option value=\"Cundinamarca - Villeta\">Villeta</option>"
      // +"<option value=\"Cundinamarca - Viotá\">Viotá</option>"
      // +"<option value=\"Cundinamarca - Yacopí\">Yacopí</option>"
      // +"<option value=\"Cundinamarca - Zipacón\">Zipacón</option>"
      // +"<option value=\"Cundinamarca - Zipaquirá\">Zipaquirá</option>"
      // +"<option value=\"Guainía - Barrancominas\">Barrancominas</option>"
      // +"<option value=\"Guainía - Cacahual\">Cacahual</option>"
      // +"<option value=\"Guainía - Inírida\">Inírida</option>"
      // +"<option value=\"Guainía - La Guadalupe\">La Guadalupe</option>"
      // +"<option value=\"Guainía - Mapiripana\">Mapiripana</option>"
      // +"<option value=\"Guainía - Morichal Nuevo\">Morichal Nuevo</option>"
      // +"<option value=\"Guainía - Pana Pana\">Pana Pana</option>"
      // +"<option value=\"Guainía - Puerto Colombia\">Puerto Colombia</option>"
      // +"<option value=\"Guainía - San Felipe\">San Felipe</option>"
      // +"<option value=\"Guaviare - Calamar\">Calamar</option>"
      // +"<option value=\"Guaviare - El Retorno\">El Retorno</option>"
      // +"<option value=\"Guaviare - Miraflores\">Miraflores</option>"
      // +"<option value=\"Guaviare - San José del Guaviare\">San José del Guaviare</option>"
      // +"<option value=\"Huila - Acevedo\">Acevedo</option>"
      // +"<option value=\"Huila - Agrado\">Agrado</option>"
      // +"<option value=\"Huila - Aipe\">Aipe</option>"
      // +"<option value=\"Huila - Algeciras\">Algeciras</option>"
      // +"<option value=\"Huila - Altamira\">Altamira</option>"
      // +"<option value=\"Huila - Baraya\">Baraya</option>"
      // +"<option value=\"Huila - Campoalegre\">Campoalegre</option>"
      // +"<option value=\"Huila - Colombia\">Colombia</option>"
      // +"<option value=\"Huila - El Pital\">El Pital</option>"
      // +"<option value=\"Huila - Elías\">Elías</option>"
      // +"<option value=\"Huila - Garzón\">Garzón</option>"
      // +"<option value=\"Huila - Gigante\">Gigante</option>"
      // +"<option value=\"Huila - Guadalupe\">Guadalupe</option>"
      // +"<option value=\"Huila - Hobo\">Hobo</option>"
      // +"<option value=\"Huila - Íquira\">Íquira</option>"
      // +"<option value=\"Huila - Isnos\">Isnos</option>"
      // +"<option value=\"Huila - La Argentina\">La Argentina</option>"
      // +"<option value=\"Huila - La Plata\">La Plata</option>"
      // +"<option value=\"Huila - Nátaga\">Nátaga</option>"
      // +"<option value=\"Huila - Neiva\">Neiva</option>"
      // +"<option value=\"Huila - Oporapa\">Oporapa</option>"
      // +"<option value=\"Huila - Paicol\">Paicol</option>"
      // +"<option value=\"Huila - Palermo\">Palermo</option>"
      // +"<option value=\"Huila - Palestina\">Palestina</option>"
      // +"<option value=\"Huila - Pitalito\">Pitalito</option>"
      // +"<option value=\"Huila - Rivera\">Rivera</option>"
      // +"<option value=\"Huila - Saladoblanco\">Saladoblanco</option>"
      // +"<option value=\"Huila - San Agustín\">San Agustín</option>"
      // +"<option value=\"Huila - Santa María\">Santa María</option>"
      // +"<option value=\"Huila - Suaza\">Suaza</option>"
      // +"<option value=\"Huila - Tarqui\">Tarqui</option>"
      // +"<option value=\"Huila - Tello\">Tello</option>"
      // +"<option value=\"Huila - Teruel\">Teruel</option>"
      // +"<option value=\"Huila - Tesalia\">Tesalia</option>"
      // +"<option value=\"Huila - Timaná\">Timaná</option>"
      // +"<option value=\"Huila - Villavieja\">Villavieja</option>"
      // +"<option value=\"Huila - Yaguará\">Yaguará</option>"
      // +"<option value=\"La Guajira - Albania\">Albania</option>"
      // +"<option value=\"La Guajira - Barrancas\">Barrancas</option>"
      // +"<option value=\"La Guajira - Dibulla\">Dibulla</option>"
      // +"<option value=\"La Guajira - Distracción\">Distracción</option>"
      // +"<option value=\"La Guajira - El Molino\">El Molino</option>"
      // +"<option value=\"La Guajira - Fonseca\">Fonseca</option>"
      // +"<option value=\"La Guajira - Hatonuevo\">Hatonuevo</option>"
      // +"<option value=\"La Guajira - La Jagua del Pilar\">La Jagua del Pilar</option>"
      // +"<option value=\"La Guajira - Maicao\">Maicao</option>"
      // +"<option value=\"La Guajira - Manaure\">Manaure</option>"
      // +"<option value=\"La Guajira - Riohacha\">Riohacha</option>"
      // +"<option value=\"La Guajira - San Juan del Cesar\">San Juan del Cesar</option>"
      // +"<option value=\"La Guajira - Uribia\">Uribia</option>"
      // +"<option value=\"La Guajira - Urumita\">Urumita</option>"
      // +"<option value=\"La Guajira - Villanueva\">Villanueva</option>"
      // +"<option value=\"Magdalena - Algarrobo\">Algarrobo</option>"
      // +"<option value=\"Magdalena - Aracataca\">Aracataca</option>"
      // +"<option value=\"Magdalena - Ariguaní\">Ariguaní</option>"
      // +"<option value=\"Magdalena - Cerro de San Antonio\">Cerro de San Antonio</option>"
      // +"<option value=\"Magdalena - Chibolo\">Chibolo</option>"
      // +"<option value=\"Magdalena - Ciénaga\">Ciénaga</option>"
      // +"<option value=\"Magdalena - Concordia\">Concordia</option>"
      // +"<option value=\"Magdalena - El Banco\">El Banco</option>"
      // +"<option value=\"Magdalena - El Piñón\">El Piñón</option>"
      // +"<option value=\"Magdalena - El Retén\">El Retén</option>"
      // +"<option value=\"Magdalena - Fundación\">Fundación</option>"
      // +"<option value=\"Magdalena - Guamal\">Guamal</option>"
      // +"<option value=\"Magdalena - Nuava Granada\">Nuava Granada</option>"
      // +"<option value=\"Magdalena - Pedraza\">Pedraza</option>"
      // +"<option value=\"Magdalena - Pijiño del Carmen\">Pijiño del Carmen</option>"
      // +"<option value=\"Magdalena - Pivijay\">Pivijay</option>"
      // +"<option value=\"Magdalena - Plato\">Plato</option>"
      // +"<option value=\"Magdalena - Pueblo Viejo\">Pueblo Viejo</option>"
      // +"<option value=\"Magdalena - Remolino\">Remolino</option>"
      // +"<option value=\"Magdalena - Sabanas de San Ángel\">Sabanas de San Ángel</option>"
      // +"<option value=\"Magdalena - Salamina\">Salamina</option>"
      // +"<option value=\"Magdalena - San Sebastián de Buenavista\">San Sebastián de Buenavista</option>"
      // +"<option value=\"Magdalena - San Zenón\">San Zenón</option>"
      // +"<option value=\"Magdalena - Santa Ana\">Santa Ana</option>"
      // +"<option value=\"Magdalena - Santa Bárbara de Pinto\">Santa Bárbara de Pinto</option>"
      // +"<option value=\"Magdalena - Santa Marta\">Santa Marta</option>"
      // +"<option value=\"Magdalena - Sitionuevo\">Sitionuevo</option>"
      // +"<option value=\"Magdalena - Tenerife\">Tenerife</option>"
      // +"<option value=\"Magdalena - Zapayán\">Zapayán</option>"
      // +"<option value=\"Magdalena - Zona Bananera\">Zona Bananera</option>"
      // +"<option value=\"Meta - Acacías\">Acacías</option>"
      // +"<option value=\"Meta - Barranca de Upía\">Barranca de Upía</option>"
      // +"<option value=\"Meta - Cabuyaro\">Cabuyaro</option>"
      // +"<option value=\"Meta - Castilla La Nueva\">Castilla La Nueva</option>"
      // +"<option value=\"Meta - Cubarral\">Cubarral</option>"
      // +"<option value=\"Meta - Cumaral\">Cumaral</option>"
      // +"<option value=\"Meta - El Calvario\">El Calvario</option>"
      // +"<option value=\"Meta - El Castillo\">El Castillo</option>"
      // +"<option value=\"Meta - El Dorado\">El Dorado</option>"
      // +"<option value=\"Meta - Fuente de Oro\">Fuente de Oro</option>"
      // +"<option value=\"Meta - Granada\">Granada</option>"
      // +"<option value=\"Meta - Guamal\">Guamal</option>"
      // +"<option value=\"Meta - La Macarena\">La Macarena</option>"
      // +"<option value=\"Meta - La Uribe\">La Uribe</option>"
      // +"<option value=\"Meta - Lejanías\">Lejanías</option>"
      // +"<option value=\"Meta - Mapiripán\">Mapiripán</option>"
      // +"<option value=\"Meta - Mesetas\">Mesetas</option>"
      // +"<option value=\"Meta - Puerto Concordia\">Puerto Concordia</option>"
      // +"<option value=\"Meta - Puerto Gaitán\">Puerto Gaitán</option>"
      // +"<option value=\"Meta - Puerto Lleras\">Puerto Lleras</option>"
      // +"<option value=\"Meta - Puerto López\">Puerto López</option>"
      // +"<option value=\"Meta - Puerto Rico\">Puerto Rico</option>"
      // +"<option value=\"Meta - Restrepo\">Restrepo</option>"
      // +"<option value=\"Meta - San Carlos de Guaroa\">San Carlos de Guaroa</option>"
      // +"<option value=\"Meta - San Juan de Arama\">San Juan de Arama</option>"
      // +"<option value=\"Meta - San Juanito\">San Juanito</option>"
      // +"<option value=\"Meta - San Martín\">San Martín</option>"
      // +"<option value=\"Meta - Villavicencio\">Villavicencio</option>"
      // +"<option value=\"Meta - Vista Hermosa\">Vista Hermosa</option>"
      // +"<option value=\"Nariño - Aldana\">Aldana</option>"
      // +"<option value=\"Nariño - Ancuya\">Ancuya</option>"
      // +"<option value=\"Nariño - Arboleda\">Arboleda</option>"
      // +"<option value=\"Nariño - Barbacoas\">Barbacoas</option>"
      // +"<option value=\"Nariño - Belén\">Belén</option>"
      // +"<option value=\"Nariño - Buesaco\">Buesaco</option>"
      // +"<option value=\"Nariño - Chachagüí\">Chachagüí</option>"
      // +"<option value=\"Nariño - Colón\">Colón</option>"
      // +"<option value=\"Nariño - Consacá\">Consacá</option>"
      // +"<option value=\"Nariño - Contadero\">Contadero</option>"
      // +"<option value=\"Nariño - Córdoba\">Córdoba</option>"
      // +"<option value=\"Nariño - Cuaspud\">Cuaspud</option>"
      // +"<option value=\"Nariño - Cumbal\">Cumbal</option>"
      // +"<option value=\"Nariño - Cumbitara\">Cumbitara</option>"
      // +"<option value=\"Nariño - El Charco\">El Charco</option>"
      // +"<option value=\"Nariño - El Peñol\">El Peñol</option>"
      // +"<option value=\"Nariño - El Rosario\">El Rosario</option>"
      // +"<option value=\"Nariño - El Tablón\">El Tablón</option>"
      // +"<option value=\"Nariño - El Tambo\">El Tambo</option>"
      // +"<option value=\"Nariño - Francisco Pizarro\">Francisco Pizarro</option>"
      // +"<option value=\"Nariño - Funes\">Funes</option>"
      // +"<option value=\"Nariño - Guachucal\">Guachucal</option>"
      // +"<option value=\"Nariño - Guaitarilla\">Guaitarilla</option>"
      // +"<option value=\"Nariño - Gualmatán\">Gualmatán</option>"
      // +"<option value=\"Nariño - Iles\">Iles</option>"
      // +"<option value=\"Nariño - Imués\">Imués</option>"
      // +"<option value=\"Nariño - Ipiales\">Ipiales</option>"
      // +"<option value=\"Nariño - La Cruz\">La Cruz</option>"
      // +"<option value=\"Nariño - La Florida\">La Florida</option>"
      // +"<option value=\"Nariño - La Llanada\">La Llanada</option>"
      // +"<option value=\"Nariño - La Tola\">La Tola</option>"
      // +"<option value=\"Nariño - La Unión\">La Unión</option>"
      // +"<option value=\"Nariño - Leiva\">Leiva</option>"
      // +"<option value=\"Nariño - Linares\">Linares</option>"
      // +"<option value=\"Nariño - Los Andes\">Los Andes</option>"
      // +"<option value=\"Nariño - Magüí\">Magüí</option>"
      // +"<option value=\"Nariño - Mallama\">Mallama</option>"
      // +"<option value=\"Nariño - Mosquera\">Mosquera</option>"
      // +"<option value=\"Nariño - Nariño\">Nariño</option>"
      // +"<option value=\"Nariño - Olaya Herrera\">Olaya Herrera</option>"
      // +"<option value=\"Nariño - Ospina\">Ospina</option>"
      // +"<option value=\"Nariño - Pasto\">Pasto</option>"
      // +"<option value=\"Nariño - Policarpa\">Policarpa</option>"
      // +"<option value=\"Nariño - Potosí\">Potosí</option>"
      // +"<option value=\"Nariño - Providencia\">Providencia</option>"
      // +"<option value=\"Nariño - Puerres\">Puerres</option>"
      // +"<option value=\"Nariño - Pupiales\">Pupiales</option>"
      // +"<option value=\"Nariño - Ricaurte\">Ricaurte</option>"
      // +"<option value=\"Nariño - Roberto Payán\">Roberto Payán</option>"
      // +"<option value=\"Nariño - Samaniego\">Samaniego</option>"
      // +"<option value=\"Nariño - San Bernardo\">San Bernardo</option>"
      // +"<option value=\"Nariño - San José de Albán\">San José de Albán</option>"
      // +"<option value=\"Nariño - San Lorenzo\">San Lorenzo</option>"
      // +"<option value=\"Nariño - San Pablo\">San Pablo</option>"
      // +"<option value=\"Nariño - San Pedro de Cartago\">San Pedro de Cartago</option>"
      // +"<option value=\"Nariño - Sandoná\">Sandoná</option>"
      // +"<option value=\"Nariño - Santa Bárbara\">Santa Bárbara</option>"
      // +"<option value=\"Nariño - Santacruz\">Santacruz</option>"
      // +"<option value=\"Nariño - Sapuyes\">Sapuyes</option>"
      // +"<option value=\"Nariño - Taminango\">Taminango</option>"
      // +"<option value=\"Nariño - Tangua\">Tangua</option>"
      // +"<option value=\"Nariño - Tumaco\">Tumaco</option>"
      // +"<option value=\"Nariño - Túquerres\">Túquerres</option>"
      // +"<option value=\"Nariño - Yacuanquer\">Yacuanquer</option>"
      // +"<option value=\"Norte de Santander - Ábrego\">Ábrego</option>"
      // +"<option value=\"Norte de Santander - Arboledas\">Arboledas</option>"
      // +"<option value=\"Norte de Santander - Bochalema\">Bochalema</option>"
      // +"<option value=\"Norte de Santander - Bucarasica\">Bucarasica</option>"
      // +"<option value=\"Norte de Santander - Cáchira\">Cáchira</option>"
      // +"<option value=\"Norte de Santander - Cácota\">Cácota</option>"
      // +"<option value=\"Norte de Santander - Chinácota\">Chinácota</option>"
      // +"<option value=\"Norte de Santander - Chitagá\">Chitagá</option>"
      // +"<option value=\"Norte de Santander - Convención\">Convención</option>"
      // +"<option value=\"Norte de Santander - Cúcuta\">Cúcuta</option>"
      // +"<option value=\"Norte de Santander - Cucutilla\">Cucutilla</option>"
      // +"<option value=\"Norte de Santander - Durania\">Durania</option>"
      // +"<option value=\"Norte de Santander - El Carmen\">El Carmen</option>"
      // +"<option value=\"Norte de Santander - El Tarra\">El Tarra</option>"
      // +"<option value=\"Norte de Santander - El Zulia\">El Zulia</option>"
      // +"<option value=\"Norte de Santander - Gramalote\">Gramalote</option>"
      // +"<option value=\"Norte de Santander - Hacarí\">Hacarí</option>"
      // +"<option value=\"Norte de Santander - Herrán\">Herrán</option>"
      // +"<option value=\"Norte de Santander - La Esperanza\">La Esperanza</option>"
      // +"<option value=\"Norte de Santander - La Playa de Belén\">La Playa de Belén</option>"
      // +"<option value=\"Norte de Santander - Labateca\">Labateca</option>"
      // +"<option value=\"Norte de Santander - Los Patios\">Los Patios</option>"
      // +"<option value=\"Norte de Santander - Lourdes\">Lourdes</option>"
      // +"<option value=\"Norte de Santander - Mutiscua\">Mutiscua</option>"
      // +"<option value=\"Norte de Santander - Ocaña\">Ocaña</option>"
      // +"<option value=\"Norte de Santander - Pamplona\">Pamplona</option>"
      // +"<option value=\"Norte de Santander - Pamplonita\">Pamplonita</option>"
      // +"<option value=\"Norte de Santander - Puerto Santander\">Puerto Santander</option>"
      // +"<option value=\"Norte de Santander - Ragonvalia\">Ragonvalia</option>"
      // +"<option value=\"Norte de Santander - Salazar de Las Palmas\">Salazar de Las Palmas</option>"
      // +"<option value=\"Norte de Santander - San Calixto\">San Calixto</option>"
      // +"<option value=\"Norte de Santander - San Cayetano\">San Cayetano</option>"
      // +"<option value=\"Norte de Santander - Santiago\">Santiago</option>"
      // +"<option value=\"Norte de Santander - Santo Domingo de Silos\">Santo Domingo de Silos</option>"
      // +"<option value=\"Norte de Santander - Sardinata\">Sardinata</option>"
      // +"<option value=\"Norte de Santander - Teorama\">Teorama</option>"
      // +"<option value=\"Norte de Santander - Tibú\">Tibú</option>"
      // +"<option value=\"Norte de Santander - Toledo\">Toledo</option>"
      // +"<option value=\"Norte de Santander - Villa Caro\">Villa Caro</option>"
      // +"<option value=\"Norte de Santander - Villa del Rosario\">Villa del Rosario</option>"
      // +"<option value=\"Putumayo - Colón\">Colón</option>"
      // +"<option value=\"Putumayo - Mocoa\">Mocoa</option>"
      // +"<option value=\"Putumayo - Orito\">Orito</option>"
      // +"<option value=\"Putumayo - Puerto Asís\">Puerto Asís</option>"
      // +"<option value=\"Putumayo - Puerto Caicedo\">Puerto Caicedo</option>"
      // +"<option value=\"Putumayo - Puerto Guzmán\">Puerto Guzmán</option>"
      // +"<option value=\"Putumayo - Puerto Leguízamo\">Puerto Leguízamo</option>"
      // +"<option value=\"Putumayo - San Francisco\">San Francisco</option>"
      // +"<option value=\"Putumayo - San Miguel\">San Miguel</option>"
      // +"<option value=\"Putumayo - Santiago\">Santiago</option>"
      // +"<option value=\"Putumayo - Sibundoy\">Sibundoy</option>"
      // +"<option value=\"Putumayo - Valle del Guamuez\">Valle del Guamuez</option>"
      // +"<option value=\"Putumayo - Villagarzón\">Villagarzón</option>"
      // +"<option value=\"Quindío - Armenia\">Armenia</option>"
      // +"<option value=\"Quindío - Buenavista\">Buenavista</option>"
      // +"<option value=\"Quindío - Calarcá\">Calarcá</option>"
      // +"<option value=\"Quindío - Circasia\">Circasia</option>"
      // +"<option value=\"Quindío - Córdoba\">Córdoba</option>"
      // +"<option value=\"Quindío - Filandia\">Filandia</option>"
      // +"<option value=\"Quindío - Génova\">Génova</option>"
      // +"<option value=\"Quindío - La Tebaida\">La Tebaida</option>"
      // +"<option value=\"Quindío - Montenegro\">Montenegro</option>"
      // +"<option value=\"Quindío - Pijao\">Pijao</option>"
      // +"<option value=\"Quindío - Quimbaya\">Quimbaya</option>"
      // +"<option value=\"Quindío - Salento\">Salento</option>"
      // +"<option value=\"Risaralda - Apía\">Apía</option>"
      // +"<option value=\"Risaralda - Balboa\">Balboa</option>"
      // +"<option value=\"Risaralda - Belén de Umbría\">Belén de Umbría</option>"
      // +"<option value=\"Risaralda - Dosquebradas\">Dosquebradas</option>"
      // +"<option value=\"Risaralda - Guática\">Guática</option>"
      // +"<option value=\"Risaralda - La Celia\">La Celia</option>"
      // +"<option value=\"Risaralda - La Virginia\">La Virginia</option>"
      // +"<option value=\"Risaralda - Marsella\">Marsella</option>"
      // +"<option value=\"Risaralda - Mistrató\">Mistrató</option>"
      // +"<option value=\"Risaralda - Pereira\">Pereira</option>"
      // +"<option value=\"Risaralda - Pueblo Rico\">Pueblo Rico</option>"
      // +"<option value=\"Risaralda - Quinchía\">Quinchía</option>"
      // +"<option value=\"Risaralda - Santa Rosa de Cabal\">Santa Rosa de Cabal</option>"
      // +"<option value=\"Risaralda - Santuario\">Santuario</option>"
      // +"<option value=\"San Andrés y Providencia - Providencia y Santa Catalina Islas\">Providencia y Santa Catalina Islas</option>"
      // +"<option value=\"Santander - Aguada\">Aguada</option>"
      // +"<option value=\"Santander - Albania\">Albania</option>"
      // +"<option value=\"Santander - Aratoca\">Aratoca</option>"
      // +"<option value=\"Santander - Barbosa\">Barbosa</option>"
      // +"<option value=\"Santander - Barichara\">Barichara</option>"
      // +"<option value=\"Santander - Barrancabermeja\">Barrancabermeja</option>"
      // +"<option value=\"Santander - Betulia\">Betulia</option>"
      // +"<option value=\"Santander - Bolívar\">Bolívar</option>"
      // +"<option value=\"Santander - Bucaramanga\">Bucaramanga</option>"
      // +"<option value=\"Santander - Cabrera\">Cabrera</option>"
      // +"<option value=\"Santander - California\">California</option>"
      // +"<option value=\"Santander - Capitanejo\">Capitanejo</option>"
      // +"<option value=\"Santander - Carcasí\">Carcasí</option>"
      // +"<option value=\"Santander - Cepitá\">Cepitá</option>"
      // +"<option value=\"Santander - Cerrito\">Cerrito</option>"
      // +"<option value=\"Santander - Charalá\">Charalá</option>"
      // +"<option value=\"Santander - Charta\">Charta</option>"
      // +"<option value=\"Santander - Chima\">Chima</option>"
      // +"<option value=\"Santander - Chipatá\">Chipatá</option>"
      // +"<option value=\"Santander - Cimitarra\">Cimitarra</option>"
      // +"<option value=\"Santander - Concepción\">Concepción</option>"
      // +"<option value=\"Santander - Confines\">Confines</option>"
      // +"<option value=\"Santander - Contratación\">Contratación</option>"
      // +"<option value=\"Santander - Coromoro\">Coromoro</option>"
      // +"<option value=\"Santander - Curití\">Curití</option>"
      // +"<option value=\"Santander - El Carmen de Chucurí\">El Carmen de Chucurí</option>"
      // +"<option value=\"Santander - El Guacamayo\">El Guacamayo</option>"
      // +"<option value=\"Santander - El Peñón\">El Peñón</option>"
      // +"<option value=\"Santander - El Playón\">El Playón</option>"
      // +"<option value=\"Santander - El Socorro\">El Socorro</option>"
      // +"<option value=\"Santander - Encino\">Encino</option>"
      // +"<option value=\"Santander - Enciso\">Enciso</option>"
      // +"<option value=\"Santander - Florián\">Florián</option>"
      // +"<option value=\"Santander - Floridablanca\">Floridablanca</option>"
      // +"<option value=\"Santander - Galán\">Galán</option>"
      // +"<option value=\"Santander - Gámbita\">Gámbita</option>"
      // +"<option value=\"Santander - Guaca\">Guaca</option>"
      // +"<option value=\"Santander - Guadalupe\">Guadalupe</option>"
      // +"<option value=\"Santander - Guapotá\">Guapotá</option>"
      // +"<option value=\"Santander - Guavatá\">Guavatá</option>"
      // +"<option value=\"Santander - Güepsa\">Güepsa</option>"
      // +"<option value=\"Santander - Hato\">Hato</option>"
      // +"<option value=\"Santander - Jesús María\">Jesús María</option>"
      // +"<option value=\"Santander - Jordán\">Jordán</option>"
      // +"<option value=\"Santander - La Belleza\">La Belleza</option>"
      // +"<option value=\"Santander - La Paz\">La Paz</option>"
      // +"<option value=\"Santander - Landázuri\">Landázuri</option>"
      // +"<option value=\"Santander - Lebrija\">Lebrija</option>"
      // +"<option value=\"Santander - Los Santos\">Los Santos</option>"
      // +"<option value=\"Santander - Macaravita\">Macaravita</option>"
      // +"<option value=\"Santander - Málaga\">Málaga</option>"
      // +"<option value=\"Santander - Matanza\">Matanza</option>"
      // +"<option value=\"Santander - Mogotes\">Mogotes</option>"
      // +"<option value=\"Santander - Molagavita\">Molagavita</option>"
      // +"<option value=\"Santander - Ocamonte\">Ocamonte</option>"
      // +"<option value=\"Santander - Oiba\">Oiba</option>"
      // +"<option value=\"Santander - Onzaga\">Onzaga</option>"
      // +"<option value=\"Santander - Palmar\">Palmar</option>"
      // +"<option value=\"Santander - Palmas del Socorro\">Palmas del Socorro</option>"
      // +"<option value=\"Santander - Páramo\">Páramo</option>"
      // +"<option value=\"Santander - Piedecuesta\">Piedecuesta</option>"
      // +"<option value=\"Santander - Pinchote\">Pinchote</option>"
      // +"<option value=\"Santander - Puente Nacional\">Puente Nacional</option>"
      // +"<option value=\"Santander - Puerto Parra\">Puerto Parra</option>"
      // +"<option value=\"Santander - Puerto Wilches\">Puerto Wilches</option>"
      // +"<option value=\"Santander - Rionegro\">Rionegro</option>"
      // +"<option value=\"Santander - Sabana de Torres\">Sabana de Torres</option>"
      // +"<option value=\"Santander - San Andrés\">San Andrés</option>"
      // +"<option value=\"Santander - San Benito\">San Benito</option>"
      // +"<option value=\"Santander - San Gil\">San Gil</option>"
      // +"<option value=\"Santander - San Joaquín\">San Joaquín</option>"
      // +"<option value=\"Santander - San José de Miranda\">San José de Miranda</option>"
      // +"<option value=\"Santander - San Juan de Girón\">San Juan de Girón</option>"
      // +"<option value=\"Santander - San Miguel\">San Miguel</option>"
      // +"<option value=\"Santander - San Vicente de Chucurí\">San Vicente de Chucurí</option>"
      // +"<option value=\"Santander - Santa Bárbara\">Santa Bárbara</option>"
      // +"<option value=\"Santander - Santa Helena del Opón\">Santa Helena del Opón</option>"
      // +"<option value=\"Santander - Simacota\">Simacota</option>"
      // +"<option value=\"Santander - Suaita\">Suaita</option>"
      // +"<option value=\"Santander - Sucre\">Sucre</option>"
      // +"<option value=\"Santander - Suratá\">Suratá</option>"
      // +"<option value=\"Santander - Tona\">Tona</option>"
      // +"<option value=\"Santander - Valle de San José\">Valle de San José</option>"
      // +"<option value=\"Santander - Vélez\">Vélez</option>"
      // +"<option value=\"Santander - Vetas\">Vetas</option>"
      // +"<option value=\"Santander - Villanueva\">Villanueva</option>"
      // +"<option value=\"Santander - Zapatoca\">Zapatoca</option>"
      // +"<option value=\"Sucre - Buenavista\">Buenavista</option>"
      // +"<option value=\"Sucre - Caimito\">Caimito</option>"
      // +"<option value=\"Sucre - Chalán\">Chalán</option>"
      // +"<option value=\"Sucre - Colosó\">Colosó</option>"
      // +"<option value=\"Sucre - Corozal\">Corozal</option>"
      // +"<option value=\"Sucre - Coveñas\">Coveñas</option>"
      // +"<option value=\"Sucre - El Roble\">El Roble</option>"
      // +"<option value=\"Sucre - Galeras\">Galeras</option>"
      // +"<option value=\"Sucre - Guaranda\">Guaranda</option>"
      // +"<option value=\"Sucre - La Unión\">La Unión</option>"
      // +"<option value=\"Sucre - Los Palmitos\">Los Palmitos</option>"
      // +"<option value=\"Sucre - Majagual\">Majagual</option>"
      // +"<option value=\"Sucre - Morroa\">Morroa</option>"
      // +"<option value=\"Sucre - Ovejas\">Ovejas</option>"
      // +"<option value=\"Sucre - Sampués\">Sampués</option>"
      // +"<option value=\"Sucre - San Antonio de Palmito\">San Antonio de Palmito</option>"
      // +"<option value=\"Sucre - San Benito Abad\">San Benito Abad</option>"
      // +"<option value=\"Sucre - San Juan de Betulia\">San Juan de Betulia</option>"
      // +"<option value=\"Sucre - San Marcos\">San Marcos</option>"
      // +"<option value=\"Sucre - San Onofre\">San Onofre</option>"
      // +"<option value=\"Sucre - San Pedro\">San Pedro</option>"
      // +"<option value=\"Sucre - Santiago de Tolú\">Santiago de Tolú</option>"
      // +"<option value=\"Sucre - Sincé\">Sincé</option>"
      // +"<option value=\"Sucre - Sincelejo\">Sincelejo</option>"
      // +"<option value=\"Sucre - Sucre\">Sucre</option>"
      // +"<option value=\"Sucre - Tolú Viejo\">Tolú Viejo</option>"
      // +"<option value=\"Tolima - Alpujarra\">Alpujarra</option>"
      // +"<option value=\"Tolima - Alvarado\">Alvarado</option>"
      // +"<option value=\"Tolima - Ambalema\">Ambalema</option>"
      // +"<option value=\"Tolima - Anzoátegui\">Anzoátegui</option>"
      // +"<option value=\"Tolima - Armero\">Armero</option>"
      // +"<option value=\"Tolima - Ataco\">Ataco</option>"
      // +"<option value=\"Tolima - Cajamarca\">Cajamarca</option>"
      // +"<option value=\"Tolima - Carmen de Apicalá\">Carmen de Apicalá</option>"
      // +"<option value=\"Tolima - Casabianca\">Casabianca</option>"
      // +"<option value=\"Tolima - Chaparral\">Chaparral</option>"
      // +"<option value=\"Tolima - Coello\">Coello</option>"
      // +"<option value=\"Tolima - Coyaima\">Coyaima</option>"
      // +"<option value=\"Tolima - Cunday\">Cunday</option>"
      // +"<option value=\"Tolima - Dolores\">Dolores</option>"
      // +"<option value=\"Tolima - Espinal\">Espinal</option>"
      // +"<option value=\"Tolima - Falan\">Falan</option>"
      // +"<option value=\"Tolima - Flandes\">Flandes</option>"
      // +"<option value=\"Tolima - Fresno\">Fresno</option>"
      // +"<option value=\"Tolima - Guamo\">Guamo</option>"
      // +"<option value=\"Tolima - Herveo\">Herveo</option>"
      // +"<option value=\"Tolima - Honda\">Honda</option>"
      // +"<option value=\"Tolima - Ibagué\">Ibagué</option>"
      // +"<option value=\"Tolima - Icononzo\">Icononzo</option>"
      // +"<option value=\"Tolima - Lérida\">Lérida</option>"
      // +"<option value=\"Tolima - Líbano\">Líbano</option>"
      // +"<option value=\"Tolima - Mariquita\">Mariquita</option>"
      // +"<option value=\"Tolima - Melgar\">Melgar</option>"
      // +"<option value=\"Tolima - Murillo\">Murillo</option>"
      // +"<option value=\"Tolima - Natagaima\">Natagaima</option>"
      // +"<option value=\"Tolima - Ortega\">Ortega</option>"
      // +"<option value=\"Tolima - Palocabildo\">Palocabildo</option>"
      // +"<option value=\"Tolima - Piedras\">Piedras</option>"
      // +"<option value=\"Tolima - Planadas\">Planadas</option>"
      // +"<option value=\"Tolima - Prado\">Prado</option>"
      // +"<option value=\"Tolima - Purificación\">Purificación</option>"
      // +"<option value=\"Tolima - Rioblanco\">Rioblanco</option>"
      // +"<option value=\"Tolima - Roncesvalles\">Roncesvalles</option>"
      // +"<option value=\"Tolima - Rovira\">Rovira</option>"
      // +"<option value=\"Tolima - Saldaña\">Saldaña</option>"
      // +"<option value=\"Tolima - San Antonio\">San Antonio</option>"
      // +"<option value=\"Tolima - San Luis\">San Luis</option>"
      // +"<option value=\"Tolima - Santa Isabel\">Santa Isabel</option>"
      // +"<option value=\"Tolima - Suárez\">Suárez</option>"
      // +"<option value=\"Tolima - Valle de San Juan\">Valle de San Juan</option>"
      // +"<option value=\"Tolima - Venadillo\">Venadillo</option>"
      // +"<option value=\"Tolima - Villahermosa\">Villahermosa</option>"
      // +"<option value=\"Tolima - Villarrica\">Villarrica</option>"
      // +"<option value=\"Valle del Cauca - Alcalá\">Alcalá</option>"
      // +"<option value=\"Valle del Cauca - Andalucía\">Andalucía</option>"
      // +"<option value=\"Valle del Cauca - Ansermanuevo\">Ansermanuevo</option>"
      // +"<option value=\"Valle del Cauca - Argelia\">Argelia</option>"
      // +"<option value=\"Valle del Cauca - Bolívar\">Bolívar</option>"
      // +"<option value=\"Valle del Cauca - Buenaventura\">Buenaventura</option>"
      // +"<option value=\"Valle del Cauca - Buga\">Buga</option>"
      // +"<option value=\"Valle del Cauca - Bugalagrande\">Bugalagrande</option>"
      // +"<option value=\"Valle del Cauca - Caicedonia\">Caicedonia</option>"
      // +"<option value=\"Valle del Cauca - Cali\">Cali</option>"
      // +"<option value=\"Valle del Cauca - Candelaria\">Candelaria</option>"
      // +"<option value=\"Valle del Cauca - Cartago\">Cartago</option>"
      // +"<option value=\"Valle del Cauca - Dagua\">Dagua</option>"
      // +"<option value=\"Valle del Cauca - Darién\">Darién</option>"
      // +"<option value=\"Valle del Cauca - El Águila\">El Águila</option>"
      // +"<option value=\"Valle del Cauca - El Cairo\">El Cairo</option>"
      // +"<option value=\"Valle del Cauca - El Cerrito\">El Cerrito</option>"
      // +"<option value=\"Valle del Cauca - El Dovio\">El Dovio</option>"
      // +"<option value=\"Valle del Cauca - Florida\">Florida</option>"
      // +"<option value=\"Valle del Cauca - Ginebra\">Ginebra</option>"
      // +"<option value=\"Valle del Cauca - Guacarí\">Guacarí</option>"
      // +"<option value=\"Valle del Cauca - Jamundí\">Jamundí</option>"
      // +"<option value=\"Valle del Cauca - La Cumbre\">La Cumbre</option>"
      // +"<option value=\"Valle del Cauca - La Unión\">La Unión</option>"
      // +"<option value=\"Valle del Cauca - La Victoria\">La Victoria</option>"
      // +"<option value=\"Valle del Cauca - Obando\">Obando</option>"
      // +"<option value=\"Valle del Cauca - Palmira\">Palmira</option>"
      // +"<option value=\"Valle del Cauca - Pradera\">Pradera</option>"
      // +"<option value=\"Valle del Cauca - Restrepo\">Restrepo</option>"
      // +"<option value=\"Valle del Cauca - Riofrío\">Riofrío</option>"
      // +"<option value=\"Valle del Cauca - Roldanillo\">Roldanillo</option>"
      // +"<option value=\"Valle del Cauca - San Pedro\">San Pedro</option>"
      // +"<option value=\"Valle del Cauca - Sevilla\">Sevilla</option>"
      // +"<option value=\"Valle del Cauca - Toro\">Toro</option>"
      // +"<option value=\"Valle del Cauca - Trujillo\">Trujillo</option>"
      // +"<option value=\"Valle del Cauca - Tuluá\">Tuluá</option>"
      // +"<option value=\"Valle del Cauca - Ulloa\">Ulloa</option>"
      // +"<option value=\"Valle del Cauca - Versalles\">Versalles</option>"
      // +"<option value=\"Valle del Cauca - Vijes\">Vijes</option>"
      // +"<option value=\"Valle del Cauca - Yotoco\">Yotoco</option>"
      // +"<option value=\"Valle del Cauca - Yumbo\">Yumbo</option>"
      // +"<option value=\"Valle del Cauca - Zarzal\">Zarzal</option>"
      // +"<option value=\"Vaupés - Carurú\">Carurú</option>"
      // +"<option value=\"Vaupés - Mitú\">Mitú</option>"
      // +"<option value=\"Vaupés - Pacoa\">Pacoa</option>"
      // +"<option value=\"Vaupés - Papunaua\">Papunaua</option>"
      // +"<option value=\"Vaupés - Taraira\">Taraira</option>"
      // +"<option value=\"Vaupés - Yavaraté\">Yavaraté</option>"
      // +"<option value=\"Vichada - Cumaribo\">Cumaribo</option>"
      // +"<option value=\"Vichada - La Primavera\">La Primavera</option>"
      // +"<option value=\"Vichada - Puerto Carreño\">Puerto Carreño</option>"
      // +"<option value=\"Vichada - Santa Rosalía\">Santa Rosalía</option>";
     let final = "Seleccione...";
     let aux = lst.split("<option");
     let departament = (document.getElementById(idDepartament) as HTMLInputElement).value;
     for (let i=0; i<aux.length; i++) {
     if (aux[i].toLowerCase().indexOf("\""+departament.toLowerCase()) != -1) {
     final += "<option" + aux[i];
       }
     }
     document.getElementById('city-refered').innerHTML = final
  }
}
